version: '3'

services:
  mail-api-service-v2:
    container_name: mail-api-app-v2
    build:
      context: ../
      dockerfile: v2/Dockerfile
    image: mail-api-v2:latest
    ports:
      - "1235:1235"
