version: '3'

services:
  mail-api-service-v3:
    container_name: mail-api-app-v3
    build:
      context: ../
      dockerfile: v3/Dockerfile
    image: mail-api-v3:latest
    ports:
      - "1236:1236"
